// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// arma_inverse_filter_cpp
arma::mat arma_inverse_filter_cpp(const arma::mat& U, const arma::vec& ar, const arma::vec& ma, const int d);
RcppExport SEXP _dipca_arma_inverse_filter_cpp(SEXP USEXP, SEXP arSEXP, SEXP maSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ar(arSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ma(maSEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_inverse_filter_cpp(U, ar, ma, d));
    return rcpp_result_gen;
END_RCPP
}
// smallest_eigenvector_crossprod_cpp
arma::vec smallest_eigenvector_crossprod_cpp(const arma::mat& U);
RcppExport SEXP _dipca_smallest_eigenvector_crossprod_cpp(SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    rcpp_result_gen = Rcpp::wrap(smallest_eigenvector_crossprod_cpp(U));
    return rcpp_result_gen;
END_RCPP
}
// form_blocks_cpp
List form_blocks_cpp(const NumericMatrix& X, const int s);
RcppExport SEXP _dipca_form_blocks_cpp(SEXP XSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(form_blocks_cpp(X, s));
    return rcpp_result_gen;
END_RCPP
}
// dipca_component_cpp
List dipca_component_cpp(const NumericMatrix& X, const int s, NumericVector w0, String algorithm, const double tol, const int max_iter, const int inner_power, const double inner_tol, const int verbose);
RcppExport SEXP _dipca_dipca_component_cpp(SEXP XSEXP, SEXP sSEXP, SEXP w0SEXP, SEXP algorithmSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP inner_powerSEXP, SEXP inner_tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< String >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type inner_power(inner_powerSEXP);
    Rcpp::traits::input_parameter< const double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(dipca_component_cpp(X, s, w0, algorithm, tol, max_iter, inner_power, inner_tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// dicca_component_cpp
List dicca_component_cpp(const NumericMatrix& X, const int s, NumericVector w0, const double tol, const int max_iter, const int verbose);
RcppExport SEXP _dipca_dicca_component_cpp(SEXP XSEXP, SEXP sSEXP, SEXP w0SEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(dicca_component_cpp(X, s, w0, tol, max_iter, verbose));
    return rcpp_result_gen;
END_RCPP
}
// dipls_build_Xlags_cpp
Rcpp::List dipls_build_Xlags_cpp(const arma::mat& X, int s);
RcppExport SEXP _dipca_dipls_build_Xlags_cpp(SEXP XSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(dipls_build_Xlags_cpp(X, s));
    return rcpp_result_gen;
END_RCPP
}
// dipls_build_Ts_cpp
arma::mat dipls_build_Ts_cpp(const arma::vec& t_all, int s);
RcppExport SEXP _dipca_dipls_build_Ts_cpp(SEXP t_allSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type t_all(t_allSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(dipls_build_Ts_cpp(t_all, s));
    return rcpp_result_gen;
END_RCPP
}
// dipls_weight_w_cpp
arma::vec dipls_weight_w_cpp(const Rcpp::List& Xlags, const arma::vec& beta, const arma::vec& u_s);
RcppExport SEXP _dipca_dipls_weight_w_cpp(SEXP XlagsSEXP, SEXP betaSEXP, SEXP u_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Xlags(XlagsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u_s(u_sSEXP);
    rcpp_result_gen = Rcpp::wrap(dipls_weight_w_cpp(Xlags, beta, u_s));
    return rcpp_result_gen;
END_RCPP
}
// dipls_ridge_ls_cpp
Rcpp::List dipls_ridge_ls_cpp(const arma::mat& X, const arma::mat& y, double lambda);
RcppExport SEXP _dipca_dipls_ridge_ls_cpp(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(dipls_ridge_ls_cpp(X, y, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dipca_arma_inverse_filter_cpp", (DL_FUNC) &_dipca_arma_inverse_filter_cpp, 4},
    {"_dipca_smallest_eigenvector_crossprod_cpp", (DL_FUNC) &_dipca_smallest_eigenvector_crossprod_cpp, 1},
    {"_dipca_form_blocks_cpp", (DL_FUNC) &_dipca_form_blocks_cpp, 2},
    {"_dipca_dipca_component_cpp", (DL_FUNC) &_dipca_dipca_component_cpp, 9},
    {"_dipca_dicca_component_cpp", (DL_FUNC) &_dipca_dicca_component_cpp, 6},
    {"_dipca_dipls_build_Xlags_cpp", (DL_FUNC) &_dipca_dipls_build_Xlags_cpp, 2},
    {"_dipca_dipls_build_Ts_cpp", (DL_FUNC) &_dipca_dipls_build_Ts_cpp, 2},
    {"_dipca_dipls_weight_w_cpp", (DL_FUNC) &_dipca_dipls_weight_w_cpp, 3},
    {"_dipca_dipls_ridge_ls_cpp", (DL_FUNC) &_dipca_dipls_ridge_ls_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dipca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
